language: python
python:
- '2.7'
install:
- pip install pipenv
- pipenv install --dev
script:
- bin/run-tests.sh
deploy:
  skip_cleanup: true
  provider: pypi
  user: david.lukac
  password:
    secure: HnftjCgEUPADrPCTS+ZB03zCMdVPQ26lgeaB7Wx9pELJnVJV1QcFfxhZHYVAIv4sRBsENniDtzfXSYheVfvMTQTmgx0VEp1dNwRLemGlRmAnpQ6U58FIC3Y5f0ZNBPFE8JN13MeekrKr4rOtCyttn2k4pquf/hjElzyu1cY+m0fM0gslQAMg+LSvN/WYRxDWCzvM5GIxWZ5EGkLz0Q20lV27GXHnggb3bJBicxrCWEr8Kb7VybPIk6V35Aedfqqm+Sg/czsABqi3RS075I5fNTH2NENyy7809EyxK0aVeCwSLviMAF+Axy4tNjpEDsVe8NBToYCRWo8WY9NfvQ8Z8OJgrmcbbJRvEiHefNNdkjfFWE80IAdR9AOiVziO8j47adhvYHYKvUZ7t8aSB4C7Zoi4uODnEJ2812ekKGaU1b/Pmei8/rvd5CoEDhe+JrbAtGbedfT8942mjSUgEdZwYQHx2AeI9UT5WQ7nk+WRXCUDplBJC5MSw8skA4rK5QrjKSYqjIXYX13MBKSeh72rEuIqTy5noZ1fz5QTOnf32k9eCQ4j37n6aJM/9Q6XxAzKV0SE3G56/ZXwqpMdYd3+7Lu6D/MBkt239v7dUl+T5Px+NuRLSFm/5CUnZnNJvK1R5kR3Khv61otGrdgo3dlaGvU9kX3gNj2ysYaEDTwA39s=
