language: python
python:
- '2.7'
install:
- pip install pipenv
- pipenv install --dev
script:
- bin/run-tests.sh
deploy:
  skip_cleanup: true
  provider: pypi
  user: david.lukac
  password:
    secure: QvU2XJAosKWLWTk+FMim7G8xTa7jjifFf399JXX/W+zrKdk16z01DCFDSOUlSPtXLYUcSzdTXjzBxAn0ruAVyS88AnpgzaLQYOFsoTV7Z+ZuRJ2Atavp9d5Vs5sBwIIKyL5FCAgzzmx/1UYrNYTNmBliAY86EdaAVMRFfCobf9Vb9J70wz8SCN+aWXuq2hLGzoaBv4zRx3Jqc60HUvcmbQCE8TjiyNf4iw0n8NIBvQ5RZvg3tjSP80Jn2LRp928a2pm/orrPuOLcEt72QwleArs1Dy4Jtjueq9Ud7a2mH5sKWz8QHrFnwnO3QzIElvObFQwiF88I+6n0lz6Z+bBDHIDrDVPU5w+HMEFURY/QmzpNa10dT1QdfHv8+x5f7StSZpuTx4BiBiYL4puxIGrhYoTlNheqrM9Rz3L5XwLmiok2w40gdHn3ROGCVH+gJgvnQrrD+f9gV5lIN41GlhdWGSbsQNRUQoIeZSjY+N5iDJaFZw57YtjXSf/fuMKxAoI0T5KQBBrYp8w1epPbqiZdrKAWbg2Kweu0Fw2fI/ibOcokknDaXJVsuM+8VndUWmw2RKa4rmvlr1Cm13S+wSgKG/Us0tJcDtlaHkB20vb8zPMab4aErSut+PXdnzELTGFDCt9JNFpBjJW8MbzuvFce0lsHzLrlBTh9wpY4c/jWgi4=
